base_model: pythia-410m
variant: ~
cache: /mnt/hdd-0/circuits-over-time/model_cache/ct
checkpoint_schedule:
  - 2000
  - 3000
  - 4000
  - 8000
  - 16000
  - 32000
  - 64000
  - 143000
start_layer: 3
device: cuda:6
overwrite: false