{
  "model_name": "pythia-12b",
  "model_tl_name": "pythia-12b",
  "cache_dir": "model_cache",
  #"cache_dir": "/media/curttigges/project-files/projects/circuits",
  "checkpoint_schedule": "exp_plus_detail",
  "batch_size": 10,
  "large_model": True,
  "tasks": ["ioi", "greater_than", "sentiment_cont", "sentiment_class", "sst"]
}
