{
  "model_name": "pythia-160m-seed3",
  "model_tl_name": "pythia-160m",
  "cache_dir": "/fsx/home-curt/saved_models",
  "checkpoint_schedule": "exp_plus_detail",
  "data_path": "./data/simple_dataset.txt",
}
