{
  "model_name": "pythia-410m",
  "model_tl_name": "pythia-410m",
  "cache_dir": "model_cache",
  "checkpoint_schedule": "exp_plus_detail",
  "batch_size": 70,
  "tasks": ["ioi", "greater_than", "sentiment_cont", "sentiment_class", "sst"]
}
