model: pythia-160m-weight-seed1
eval_metric: logit_diff
batch_size: 32
ckpt: 143000
top_n: 100
ckpt_schedule: other
cache_dir: model_cache
verify: true
start: 25
end: 1600
step: 25
overwrite: true
search_type: linear
