model: pythia-160m
alt_model: EleutherAI/pythia-160m-seed3
eval_metric: logit_diff
batch_size: 32
ckpt: 143000
top_n: 100
ckpt_schedule: other
cache_dir: model_cache
verify: true
start: 25
end: 1600
step: 25
overwrite: false
search_type: linear
