model: pythia-2.8b
eval_metric: logit_diff
batch_size: 8
ckpt: 143000
top_n: 100
ckpt_schedule: sparse
cache_dir: model_cache
verify: true
start: 25
end: 1600
step: 25
overwrite: false
search_type: linear
