model: pythia-70m
eval_metric: logit_diff
batch_size: 32
ckpt: 143000
top_n: 100
ckpt_schedule: late_start_all
cache_dir: model_cache
verify: true
start: 25
end: 1600
step: 25
overwrite: true
search_type: linear
